let alpha = [
  {
    name: {
      common: "Colombia",
      official: "Republic of Colombia",
      nativeName: {
        spa: { official: "República de Colombia", common: "Colombia" },
      },
    },
    tld: [".co"],
    cca2: "CO",
    ccn3: "170",
    cca3: "COL",
    cioc: "COL",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { COP: { name: "Colombian peso", symbol: "$" } },
    idd: { root: "+5", suffixes: ["7"] },
    capital: ["Bogotá"],
    altSpellings: ["CO", "Republic of Colombia", "República de Colombia"],
    region: "Americas",
    subregion: "South America",
    languages: { spa: "Spanish" },
    translations: {
      ara: { official: "جمهورية كولومبيا", common: "كولومبيا" },
      bre: { official: "Republik Kolombia", common: "Kolombia" },
      ces: { official: "Kolumbijská republika", common: "Kolumbie" },
      cym: { official: "Gweriniaeth Colombia", common: "Colombia" },
      deu: { official: "Republik Kolumbien", common: "Kolumbien" },
      est: { official: "Colombia Vabariik", common: "Colombia" },
      fin: { official: "Kolumbian tasavalta", common: "Kolumbia" },
      fra: { official: "République de Colombie", common: "Colombie" },
      hrv: { official: "Republika Kolumbija", common: "Kolumbija" },
      hun: { official: "Kolumbiai Köztársaság", common: "Kolumbia" },
      ita: { official: "Repubblica di Colombia", common: "Colombia" },
      jpn: { official: "コロンビア共和国", common: "コロンビア" },
      kor: { official: "콜롬비아 공화국", common: "콜롬비아" },
      nld: { official: "Republiek Colombia", common: "Colombia" },
      per: { official: "جمهوری کلمبیا", common: "کلمبیا" },
      pol: { official: "Republika Kolumbii", common: "Kolumbia" },
      por: { official: "República da Colômbia", common: "Colômbia" },
      rus: { official: "Республика Колумбия", common: "Колумбия" },
      slk: { official: "Kolumbijská republika", common: "Kolumbia" },
      spa: { official: "República de Colombia", common: "Colombia" },
      srp: { official: "Република Колумбија", common: "Колумбија" },
      swe: { official: "Republiken Colombia", common: "Colombia" },
      tur: { official: "Kolombiya Cumhuriyeti", common: "Kolombiya" },
      urd: { official: "جمہوریہ کولمبیا", common: "کولمبیا" },
      zho: { official: "哥伦比亚共和国", common: "哥伦比亚" },
    },
    latlng: [4.0, -72.0],
    landlocked: false,
    borders: ["BRA", "ECU", "PAN", "PER", "VEN"],
    area: 1141748.0,
    demonyms: {
      eng: { f: "Colombian", m: "Colombian" },
      fra: { f: "Colombienne", m: "Colombien" },
    },
    flag: "\uD83C\uDDE8\uD83C\uDDF4",
    maps: {
      googleMaps: "https://goo.gl/maps/RdwTG8e7gPwS62oR6",
      openStreetMaps: "https://www.openstreetmap.org/relation/120027",
    },
    population: 50882884,
    gini: { 2019: 51.3 },
    fifa: "COL",
    car: { signs: ["CO"], side: "right" },
    timezones: ["UTC-05:00"],
    continents: ["South America"],
    flags: {
      png: "https://flagcdn.com/w320/co.png",
      svg: "https://flagcdn.com/co.svg",
      alt: "The flag of Colombia is composed of three horizontal bands of yellow, blue and red, with the yellow band twice the height of the other two bands.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/co.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/co.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [4.71, -74.07] },
  },
];
